# Étape 1 : Build du frontend
FROM node:18 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# Étape 2 : Serveur web léger (Nginx)
FROM nginx:alpine

# Copier les fichiers du build React dans Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Exposer le port web
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
